In [1]:
from Load_and_fill import load_and_fill_0, load_and_fill_median

file = '../train.csv'

In [2]:
data = load_and_fill_0(file)

data.head()

,BS,CALI,DCAL,DEPTH_MD,DRHO,DTC,DTS,FORCE_2020_LITHOFACIES_CONFIDENCE,FORCE_2020_LITHOFACIES_LITHOLOGY,FORMATION,...,ROP,ROPA,RSHA,RXO,SGR,SP,WELL,X_LOC,Y_LOC,Z_LOC
0,0.0,19.480835,0.0,494.528,-0.574928,161.131180,0.0,1.0,65000.0,0,...,34.636410,0.0,0.0,0.0,0.0,24.612379,15/9-13,437641.96875,6470972.5,-469.501831
1,0.0,19.468800,0.0,494.680,-0.570188,160.603470,0.0,1.0,65000.0,0,...,34.636410,0.0,0.0,0.0,0.0,23.895531,15/9-13,437641.96875,6470972.5,-469.653809
2,0.0,19.468800,0.0,494.832,-0.574245,160.173615,0.0,1.0,65000.0,0,...,34.779556,0.0,0.0,0.0,0.0,23.916357,15/9-13,437641.96875,6470972.5,-469.805786
3,0.0,19.459282,0.0,494.984,-0.586315,160.149429,0.0,1.0,65000.0,0,...,39.965164,0.0,0.0,0.0,0.0,23.793688,15/9-13,437641.96875,6470972.5,-469.957794
4,0.0,19.453100,0.0,495.136,-0.597914,160.128342,0.0,1.0,65000.0,0,...,57.483765,0.0,0.0,0.0,0.0,24.104078,15/9-13,437641.96875,6470972.5,-470.109772

In [3]:
test = load_and_fill_median(file)

Filling missing values from curves:
['RSHA', 'RMED', 'RDEP', 'RHOB', 'GR', 'NPHI', 'DTC', 'PEF', 'RXO']
----------------------------------------
Group by: ['WELL', 'FORMATION']

C:\Users\tkngu\anaconda3\lib\site-packages\pandas\core\frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

Total number of missing values: 1804929
========================================
Group by: ['WELL', 'GROUP']
Total number of missing values: 1635929
========================================
Group by: ['WELL']
Total number of missing values: 953554
========================================
Group by: ['FORMATION']
Total number of missing values: 16906
========================================
Group by: ['GROUP']
Total number of missing values: 1205
========================================

In [4]:
test.head()

,BS,CALI,DCAL,DEPTH_MD,DRHO,DTC,DTS,FORCE_2020_LITHOFACIES_CONFIDENCE,FORCE_2020_LITHOFACIES_LITHOLOGY,FORMATION,...,ROP,ROPA,RSHA,RXO,SGR,SP,WELL,X_LOC,Y_LOC,Z_LOC
2464,NaN,18.544184,NaN,869.056,0.000899,138.449585,NaN,1.0,65000.0,Utsira Fm.,...,89.089676,NaN,1.134728,1.136764,NaN,29.880625,15/9-13,437642.0625,6470974.0,-844.020447
2465,NaN,18.908665,NaN,869.208,-0.008508,140.845428,NaN,1.0,65000.0,Utsira Fm.,...,129.561523,NaN,1.134728,1.136764,NaN,29.118149,15/9-13,437642.0625,6470974.0,-844.172424
2466,NaN,19.148600,NaN,869.360,-0.011523,142.352951,NaN,1.0,30000.0,Utsira Fm.,...,453.727234,NaN,1.134728,1.136764,NaN,28.016756,15/9-13,437642.0625,6470974.0,-844.324402
2467,NaN,20.140171,NaN,869.512,-0.001811,142.852448,NaN,1.0,30000.0,Utsira Fm.,...,556.952820,NaN,1.134728,1.136764,NaN,27.235287,15/9-13,437642.0625,6470974.0,-844.476379
2468,NaN,21.352367,NaN,869.664,0.017259,143.337646,NaN,1.0,30000.0,Utsira Fm.,...,555.839600,NaN,1.134728,1.136764,NaN,27.085091,15/9-13,437642.0625,6470974.0,-844.628357